homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 460
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: Europe/Berlin

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

sensor 2:
  platform: example

# Text to speech
tts:
  platform: google

# my config
zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 20
  icon: mdi:home

zone 2:
  name: KUKA
  latitude: !secret latitude_KUKA
  longitude: !secret longitude_KUKA
  radius: 300
  icon: mdi:worker

zone 3:
  name: Seele
  latitude: !secret latitude_Seele
  longitude: !secret longitude_Seele
  radius: 100
  icon: mdi:worker

device_tracker:
  # - platform: fritz
  #  host: 192.168.1.1
  #  track_new_devices: false
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: true

mqtt:
  broker: m21.cloudmqtt.com
  port: 12863
  username: ggyaousd
  password: !secret cloudmqtt_password
  client_id: home-assi1
  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

switch ac:
  platform: example
  file_path: /tmp/ac

switch air:
  platform: example
  file_path: /tmp/air

xor_automation:
  entity_1: switch.ac
  entity_2: switch.air

media_player:
  - platform: kodi
    host: 192.168.1.120
    name: Kodi
    username: kodi
    password: !secret kodi_password
    # turn_of_action: shutdown
