homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 460
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customize

# Enables the frontend
frontend:

http:
  api_password: !secret api_password
  trusted_networks:
    - 192.168.1.0/24
    - 192.168.2.0/24
    - 192.168.3.0/24
  login_attempts_threshold: 10
  ip_ban_enabled: True

logger:
#  default: critical 
#  default: fatal
#  default: error
#  default: warning
  default: warn
#  default: info
#  default: debug
#  default: notset

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
recorder:
  purge_days: 180

# View all events in a logbook
logbook:

# Track the sun
sun:

# All sensors belong to the sensor dir
sensor: !include_dir_merge_list sensors

# All groups belong to the group dir
group: !include_dir_merge_named groups

# Text to speech
tts:
  platform: google

# my config
zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 20
  icon: mdi:home

zone 2:
  name: KUKA
  latitude: !secret latitude_KUKA
  longitude: !secret longitude_KUKA
  radius: 300
  icon: mdi:worker

zone 3:
  name: Seele
  latitude: !secret latitude_Seele
  longitude: !secret longitude_Seele
  radius: 100
  icon: mdi:worker

zone 4:
  name: Backnang
  latitude: 48.951686
  longitude: 9.415006
  radius: 50
  icon: mdi:home
  
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: true
    track_new_device: False
  - platform: fritz
    host: 192.168.1.1
    track_new_device: False
  - platform: fritz
    host: 192.168.2.1
    track_new_device: False
  - platform: fritz
    host: 192.168.3.1
    track_new_device: False

mqtt:
  broker: m21.cloudmqtt.com
  port: 12863
  username: ggyaousd
  password: !secret cloudmqtt_password
  client_id: home-assi1
  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

#switch ac:
#  platform: example
#  file_path: /tmp/ac

#switch air:
#  platform: example
#  file_path: /tmp/air

#xor_automation:
#  entity_1: switch.ac
#  entity_2: switch.air

media_player:
  - platform: kodi
    host: 192.168.1.120
    name: Kodi
    username: kodi
    password: !secret kodi_password
    # turn_of_action: shutdown
